In [1]:
import numpy as np

In [9]:
x = np.array([[2,3,4],[4,8,9]])
y =np.array([[2,4,6],[1,2,9]])

In [6]:
print(x)

[[2 3 4]
 [4 8 9]]


In [25]:
print(y)

[[2 4 6]
 [1 2 9]]


In [8]:
x. transpose()

array([[2, 4],
       [3, 8],
       [4, 9]])

In [11]:
z=np.multiply(x,y)

In [12]:
print(z)

[[ 4 12 24]
 [ 4 16 81]]


In [21]:
# multiplying by scalar matrix 
#You have to innitialize the scalar

In [19]:
b= 2
k=np.multiply(b,x)

In [20]:
print(k)

[[ 4  6  8]
 [ 8 16 18]]


In [22]:
# Addition

In [23]:
A = np.add(x,y)

In [24]:
print(A)

[[ 4  7 10]
 [ 5 10 18]]


In [26]:
#Substraction of matrices , NOT commutative

In [31]:
v= np.subtract(x,y)

In [30]:
print(v)

[[ 0 -1 -2]
 [ 3  6  0]]
