In [2]:
###Matrices

In [ ]:
#matrix, a set of numbers arranged in rows and columns so as to form a rectangular array.

In [ ]:
#Example of a matrix

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [3]:
#Types of matrices

In [4]:
#Square Matrix- has equal number of rows and collumns

In [5]:

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [6]:
#Identity Matrix- a matrix of order nxn such that each main diagonal element is equal to 1

In [10]:

x = np.array([[1, 0, 0], [0, 1, 0],[0, 0, 1]])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
#Zero Matrix

In [12]:
b = np.array([[0, 0, 0], [0, 0, 0],[0, 0, 0]])
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
#Diagnol Matrix- All of-diganols entries are zero

In [20]:
b = np.array([[9, 0, 0], [0, 8, 0],[0, 0, 1]])
print(b)

[[9 0 0]
 [0 8 0]
 [0 0 1]]


In [15]:
#indexing Matrices- 

In [21]:
b[1][1]

8